<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursesSeeder extends Seeder
{
    public function run()
    {
        $courses = [
            [
                'id' => 100,
                'code' => 'ENGL121',
                'title' => 'ENGLISH-I',
                'category' => 'UC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 101,
                'code' => 'ENGL122',
                'title' => 'ENGLISH-II',
                'category' => 'UC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 102,
                'code' => 'ENGR101',
                'title' => 'INFORMATION TECHNOLOGY AND APPLICATIONS',
                'category' => 'FC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 2,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 103,
                'code' => 'ENGR103',
                'title' => 'COMPUTER PROGRAMMING-I',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 104,
                'code' => 'ENGR104',
                'title' => 'COMPUTER PROGRAMMING-II',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 105,
                'code' => 'MATH121',
                'title' => 'CALCULUS-I',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 106,
                'code' => 'MATH122',
                'title' => 'CALCULUS-II',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 107,
                'code' => 'MATH123',
                'title' => 'DISCRETE MATHEMATICS',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 108,
                'code' => 'MATH124',
                'title' => 'LINEAR ALGEBRA',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 109,
                'code' => 'MATH225',
                'title' => 'DIFFERENTIAL EQUATIONS',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 110,
                'code' => 'MATH228',
                'title' => 'ENGINEERING MATHEMATICS',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => '3',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 111,
                'code' => 'MATH328',
                'title' => 'NUMERICAL ANALYSIS',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => '3',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 112,
                'code' => 'PHYS121',
                'title' => 'PHYSICS-I',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 113,
                'code' => 'PHYS122',
                'title' => 'PHYSICS-II',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Computer Engineering Core Courses
            [
                'id' => 200,
                'code' => 'CMPE215',
                'title' => 'ALGORITHMS AND DATA STRUCTURES',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 201,
                'code' => 'CMPE216',
                'title' => 'OBJECT ORIENTED PROGRAMMING',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 202,
                'code' => 'CMPE232',
                'title' => 'OPERATING SYSTEMS',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 203,
                'code' => 'CMPE252',
                'title' => 'ANALYSIS OF ALGORITHMS',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 4,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 204,
                'code' => 'CMPE321',
                'title' => 'MICROPROCESSORS',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 5,
                'year' => '3',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 205,
                'code' => 'CMPE322',
                'title' => 'DATA COMMUNICATION AND COMPUTER NETWORKS',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 6,
                'year' => '3',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 206,
                'code' => 'CMPE324',
                'title' => 'COMPUTER ARCHITECTURE',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => '3',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 207,
                'code' => 'CMPE341',
                'title' => 'DATABASE SYSTEMS',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 5,
                'year' => '3',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 208,
                'code' => 'CMPE403',
                'title' => 'SUMMER TRAINING',
                'category' => 'FC',
                'credits' => 0,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 2,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 209,
                'code' => 'CMPE421',
                'title' => 'PROGRAMMING LANGUAGES',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 210,
                'code' => 'CMPE431',
                'title' => 'ADVANCED COMPUTER NETWORKS',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => '4',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 211,
                'code' => 'CMPE455',
                'title' => 'MODERN PROGRAMMING PLATFORMS',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => '4',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 212,
                'code' => 'CMPE463',
                'title' => 'CLOUD COMPUTING',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 213,
                'code' => 'CMPE464',
                'title' => 'ARTIFICIAL INTELLIGENCE',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 7,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Electrical Engineering Courses
            [
                'id' => 300,
                'code' => 'ELEE211',
                'title' => 'DIGITAL LOGIC DESIGN',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 301,
                'code' => 'ELEE231',
                'title' => 'CIRCUIT THEORY-I',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 302,
                'code' => 'ELEE331',
                'title' => 'SIGNALS AND SYSTEMS',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 5,
                'year' => '3',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 303,
                'code' => 'ELEE341',
                'title' => 'ELECTRONICS-I',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 5,
                'year' => '3',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Software Engineering Courses
            [
                'id' => 400,
                'code' => 'SFWE316',
                'title' => 'INTERNET AND WEB PROGRAMMING',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => '3',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 401,
                'code' => 'SFWE343',
                'title' => 'SOFTWARE ANALYSIS AND DESIGN',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 402,
                'code' => 'SFWE415',
                'title' => 'SOFTWARE ARCHITECTURE',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Engineering Design and Ethics
            [
                'id' => 500,
                'code' => 'ENGR215',
                'title' => 'RESEARCH METHODS FOR ENGINEERING AND ARCHITECTURE',
                'category' => 'FC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 4,
                'year' => '2',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 501,
                'code' => 'ENGR401',
                'title' => 'ENGINEERING DESIGN-I',
                'category' => 'FC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 502,
                'code' => 'ENGR402',
                'title' => 'ENGINEERING DESIGN-II',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => '4',
                'ects' => 10,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 503,
                'code' => 'ENGR404',
                'title' => 'ENGINEERING ATTRIBUTES AND ETHICS',
                'category' => 'FC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 8,
                'year' => '4',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // University Core and General Education
            [
                'id' => 600,
                'code' => 'TURK131',
                'title' => 'TURKISH AS A FOREIGN LANGUAGE-I',
                'category' => 'UC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 601,
                'code' => 'TURK132',
                'title' => 'TURKISH AS A FOREIGN LANGUAGE-II',
                'category' => 'UC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 602,
                'code' => 'HIST111',
                'title' => 'ATATURK\'S PRINCIPLES AND HISTORY OF TURKISH REFORMS-I',
                'category' => 'UC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 603,
                'code' => 'HIST112',
                'title' => 'ATATURK\'S PRINCIPLES AND HISTORY OF TURKISH REFORMS-II',
                'category' => 'UC',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 604,
                'code' => 'STAT226',
                'title' => 'PROBABILITY AND STATISTICS',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => '2',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 605,
                'code' => 'OHSA206',
                'title' => 'OCCUPATIONAL HEALTH AND SAFETY',
                'category' => 'UC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => '2',
                'ects' => 3,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Electives and Optional Courses
            [
                'id' => 700,
                'code' => 'GRAD282',
                'title' => 'INTRODUCTION TO GRAPHIC DESIGN',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 701,
                'code' => 'COMP432',
                'title' => 'WIRELESS COMMUNICATION NETWORKS',
                'category' => 'AC',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => '2',
                'ects' => 7,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 702,
                'code' => 'AINE301',
                'title' => 'BASIC SEARCH METHODS',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 703,
                'code' => 'AINE312',
                'title' => 'DATA SCIENCE',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => '4',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 704,
                'code' => 'ITAL101',
                'title' => 'ITALIAN-I',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => '4',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 705,
                'code' => 'HESC109',
                'title' => 'BASIC FIRST AID',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 706,
                'code' => 'SOCI320',
                'title' => 'WOMEN AND SOCIETY',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 4,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Business and Economics Courses
            [
                'id' => 800,
                'code' => 'BUSN101',
                'title' => 'PRINCIPLES OF MANAGEMENT-I',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => '2',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 801,
                'code' => 'BUSN102',
                'title' => 'PRINCIPLES OF MANAGEMENT-II',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => '4',
                'ects' => 5,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 802,
                'code' => 'ACCT201',
                'title' => 'PRINCIPLES OF ACCOUNTING-I',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 5,
                'year' => '3',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 803,
                'code' => 'ECON101',
                'title' => 'INTRODUCTION TO ECONOMICS I',
                'category' => 'AE',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => '3',
                'ects' => 7,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // Preparatory and Proficiency Courses
            [
                'id' => 900,
                'code' => 'PREP101',
                'title' => 'ENGLISH PREP SCHOOL (A1-A1+)',
                'category' => 'UC',
                'credits' => 0,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 0,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 901,
                'code' => 'PREP102',
                'title' => 'ENGLISH PREP SCHOOL (A1+-A2)',
                'category' => 'UC',
                'credits' => 0,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 0,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 902,
                'code' => 'PREP106',
                'title' => 'ENGLISH PROFICIENCY TEST',
                'category' => 'UC',
                'credits' => 0,
                'department_id' => 2,
                'semester' => 2,
                'year' => '1',
                'ects' => 0,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 903,
                'code' => 'ENGP070',
                'title' => 'ENGLISH PROFICIENCY TEST',
                'category' => 'UC',
                'credits' => 0,
                'department_id' => 2,
                'semester' => 1,
                'year' => '1',
                'ects' => 0,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],

            // SOFTWARE ENGINEERING COURSES (Department ID: 1) - From previous seeder
            [
                'id' => 1,
                'code' => 'MATH101',
                'title' => 'CALCULUS I',
                'category' => 'FC',
                'credits' => 4,
                'department_id' => 1,
                'semester' => 1,
                'year' => '1',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            [
                'id' => 2,
                'code' => 'MATH103',
                'title' => 'DISCRETE MATHEMATICS',
                'category' => 'FC',
                'credits' => 3,
                'department_id' => 1,
                'semester' => 1,
                'year' => '1',
                'ects' => 6,
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00'
            ],
            // ... (rest of Software Engineering courses from previous seeder)

            // BUSINESS ADMINISTRATION COURSES (Department ID: 3)
            [
                'id' => 1000,
                'code' => 'ECON111',
                'title' => 'MICROECONOMICS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 3,
                'semester' => 1,
                'year' => '1',
                'ects' => 5
            ]
            // ... (rest of Business courses can be added here)
        ];

        // Insert data in batches of 20 records
        $chunks = array_chunk($courses, 20);
        foreach ($chunks as $chunk) {
            DB::table('courses')->insert($chunk);
        }
    }
}