<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursesSeeder extends Seeder
{
    public function run()
    {
        $courses = [
            [
                'id' => 1000,
                'code' => 'ECON111',
                'title' => 'MICROECONOMICS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1001,
                'code' => 'BUSN101',
                'title' => 'PRINCIPLES OF MANAGEMENT-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1002,
                'code' => 'MATH115',
                'title' => 'MATHEMATICS FOR MANAGEMENT-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1003,
                'code' => 'ITEC100',
                'title' => 'INFORMATION TECHNOLOGIES',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 1,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1004,
                'code' => 'ECON112',
                'title' => 'MACROECONOMICS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1005,
                'code' => 'BUSN102',
                'title' => 'PRINCIPLES OF MANAGEMENT-II',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1006,
                'code' => 'MATH116',
                'title' => 'MATHEMATICS FOR MANAGEMENT-II',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1007,
                'code' => 'BUSN104',
                'title' => 'BUSINESS COMMUNICATION',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1008,
                'code' => 'MARK201',
                'title' => 'INTRODUCTION TO MARKETING',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1009,
                'code' => 'ECAS201',
                'title' => 'INTRODUCTION TO BEHAVIORAL SCIENCE',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1010,
                'code' => 'LAW215',
                'title' => 'BUSINESS ETHICS AND LAW',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1011,
                'code' => 'ACCT201',
                'title' => 'PRINCIPLES OF ACCOUNTING-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1012,
                'code' => 'STAT211',
                'title' => 'BUSINESS STATISTICS-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1013,
                'code' => 'BUSN202',
                'title' => 'ORGANIZATIONAL THEORY',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1014,
                'code' => 'ECAS210',
                'title' => 'RESEARCH METHODS FOR ECONOMICS AND ADMINISTRATIVE SCIENCES',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1015,
                'code' => 'BUSN206',
                'title' => 'HUMAN RESOURCE MANAGEMENT',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1016,
                'code' => 'ACCT202',
                'title' => 'PRINCIPLES OF ACCOUNTING-II',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1017,
                'code' => 'STAT212',
                'title' => 'BUSINESS STATISTICS-II',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 4,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1018,
                'code' => 'BUSN301',
                'title' => 'PRODUCTION AND OPERATION MANAGEMENT',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1019,
                'code' => 'BUSN303',
                'title' => 'INTERNATIONAL BUSINESS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1020,
                'code' => 'FINA320',
                'title' => 'FUNDAMENTALS OF CORPORATE FINANCE',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1021,
                'code' => 'BUSN\X1',
                'title' => 'AREA ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1022,
                'code' => 'ECAS\X1',
                'title' => 'FACULTY ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1023,
                'code' => 'BUSN302',
                'title' => 'QUANTITATIVE ANALYSIS FOR MANAGEMENT',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => null,
                'ects' => 7
            ],
            [
                'id' => 1024,
                'code' => 'BUSN304',
                'title' => 'ORGANIZATIONAL BEHAVIOR',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1025,
                'code' => 'ECON310',
                'title' => 'INTERNATIONAL TRADE AND ECONOMICS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => null,
                'ects' => 7
            ],
            [
                'id' => 1026,
                'code' => 'ECAS\X2',
                'title' => 'FACULTY ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1027,
                'code' => 'UNIEX1',
                'title' => 'UNIVERSITY ELECTIVE',
                'category' => 'AE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => null,
                'ects' => 4
            ],
            [
                'id' => 1028,
                'code' => 'BUSN400',
                'title' => 'SUMMER INTERNSHIP',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 0,
                'department_id' => 2,
                'semester' => 7,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 1029,
                'code' => 'BUSN401',
                'title' => 'STRATEGIC MANAGEMENT',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1030,
                'code' => 'BUSN\X2',
                'title' => 'AREA ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1031,
                'code' => 'BUSN\X3',
                'title' => 'AREA ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1032,
                'code' => 'UNIEX2',
                'title' => 'UNIVERSITY ELECTIVE',
                'category' => 'AE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => null,
                'ects' => 4
            ],
            [
                'id' => 1033,
                'code' => 'UNIEX3',
                'title' => 'UNIVERSITY ELECTIVE',
                'category' => 'AE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 7,
                'year' => null,
                'ects' => 4
            ],
            [
                'id' => 1034,
                'code' => 'ECON412',
                'title' => 'MANAGERIAL ECONOMICS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => null,
                'ects' => 7
            ],
            [
                'id' => 1035,
                'code' => 'BUSN\X4',
                'title' => 'AREA ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1036,
                'code' => 'ECAS\X3',
                'title' => 'FACULTY ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1037,
                'code' => 'ECAS\X4',
                'title' => 'FACULTY ELECTIVE',
                'category' => 'FE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 1038,
                'code' => 'UNIEX4',
                'title' => 'UNIVERSITY ELECTIVE',
                'category' => 'AE',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => null,
                'ects' => 4
            ],
            [
                'id' => 10,
                'code' => 'MATH121',
                'title' => 'CALCULUS-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 7
            ],
            [
                'id' => 11,
                'code' => 'MATH123',
                'title' => 'DISCRETE MATHEMATICS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 6
            ],
            [
                'id' => 12,
                'code' => 'PHYS121',
                'title' => 'PHYSICS-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 1,
                'year' => null,
                'ects' => 8
            ],
            [
                'id' => 13,
                'code' => 'ENGR101',
                'title' => 'INFORMATION TECHNOLOGY AND APPLICATIONS',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 1,
                'year' => null,
                'ects' => 5
            ],
            [
                'id' => 14,
                'code' => 'ENGR103',
                'title' => 'COMPUTER PROGRAMMING-I',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 6,
                'year' => null,
                'ects' => 7
            ],
            [
                'id' => 15,
                'code' => 'ENGL121',
                'title' => 'ENGLISH-I',
                'category' => 'UC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 2,
                'year' => null,
                'ects' => 8
            ],
            [
                'id' => 16,
                'code' => 'TUOC101',
                'title' => 'TURKISH LANGUAGE-I',
                'category' => 'UC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 2,
                'department_id' => 2,
                'semester' => 4,
                'year' => null,
                'ects' => 9
            ],
            [
                'id' => 17,
                'code' => 'MATH122',
                'title' => 'CALCULUS-II',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 5,
                'year' => null,
                'ects' => 8
            ],
            [
                'id' => 18,
                'code' => 'MATH124',
                'title' => 'LINEAR ALGEBRA',
                'category' => 'FC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 3,
                'department_id' => 2,
                'semester' => 8,
                'year' => null,
                'ects' => 7
            ],
            [
                'id' => 32,
                'code' => 'CMPE252',
                'title' => 'ANALYSIS OF ALGORITHMS',
                'category' => 'AC',
                'created_at' => '2025-04-29 12:00:00',
                'updated_at' => '2025-04-29 12:00:00',
                'credits' => 4,
                'department_id' => 2,
                'semester' => 3,
                'year' => null,
                'ects' => 7
            ]
        ];

        // Insert data in batches of 20 records
        $chunks = array_chunk($courses, 20);
        foreach ($chunks as $chunk) {
            DB::table('courses')->insert($chunk);
        }
    }
}